version: '3.9'
networks:
  basic:
services:
  frontend:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile.frontend
    container_name: wms_frontend  
    image: uswccr.ccs.tencentyun.com/onlinecargo/wms-frontend:1.2
    restart: always
    privileged: true
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/baseurl.txt:/usr/share/nginx/html/statics/baseurl.txt
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - basic
  backend:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile.backend
    container_name: wms_backend
    image: uswccr.ccs.tencentyun.com/onlinecargo/wms-backend:1.2
    restart: always
    privileged: true
    volumes:
      - ./.docker/supervisord.conf:/etc/supervisor/supervisord.conf
    env_file: ./.docker/.env
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - basic
  database:
    image: mysql:5.7
    restart: always
    container_name: wms_database
    env_file: ./.docker/.env
    volumes:
      - ./.docker/database:/var/lib/mysql
      - ./.docker/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    command: '--default-authentication-plugin=mysql_native_password' 
    networks:
      - basic
