version: '3.9'
networks:
  basic:
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    container_name: greaterwms_front
    restart: always
    privileged: true
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./.docker/baseurl.txt:/usr/share/nginx/html/statics/baseurl.txt
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - basic
  backend:
    # build:
    #   context: ./
    #   dockerfile: Dockerfile.backend
    container_name: greaterwms_backend
    image: greaterwms/greaterwms:backend
    restart: always
    privileged: true
    volumes:
      - ./:/GreaterWMS/:rw
      - ./supervisord.conf:/etc/supervisor/supervisord.conf
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - basic
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otyAQox9q99RPhT2XSX^GxVm4QmQkx
    volumes:
      - ./.docker/database:/var/lib/mysql
      - ./.docker/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    command: '--default-authentication-plugin=mysql_native_password' 
    networks:
      - basic
