name: Docker Build and Push

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md' # Exclude certain files from triggering the workflow on push
  pull_request:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    # https://github.com/marketplace/actions/skip-based-on-commit-message
    # echo "version: ${VERSION}" >> $GITHUB_OUTPUT 需要 yaml 格式
    if: "startsWith(github.event.head_commit.message, 'release')"
    steps:
      - name: Extract version number
        id: extract_version
        run: |
          VERSION=$(echo ${{ github.event.head_commit.message }} | sed -n 's/release: v\([0-9]\+\.[0-9]\+\)/\1/p')
          echo "version: ${VERSION}" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Tencent Container Registry
        uses: docker/login-action@v2
        with:
          registry: uswccr.ccs.tencentyun.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: uswccr.ccs.tencentyun.com/onlinecargo/wms-frontend:${{ steps.extract_version.outputs.version }}
          file: Dockerfile.frontend
          context: .

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: uswccr.ccs.tencentyun.com/onlinecargo/wms-backend:${{ steps.extract_version.outputs.version }}
          file: Dockerfile.backend
          context: .

